#!/usr/bin/env python3
# Copyright (c) 2026, Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
#
# ck_post_build.py — post-build step for CK JIT mode.
#
#   1. Compile ck_jit_runtime.cpp.
#   2. Link libmha_fwd.so and libmha_bwd.so together with the host object
#      files compiled by ninja (mha_fwd.cu etc.) and the rewritten api .o
#      files compiled by ck_build_interceptor during the intercept phase.
#   3. Optionally validate that all kernel names in manifest api entries exist
#      as blob entries, and flag unused blobs (in manifest but unreferenced).
#
# API file rewriting and compilation now happen in ck_build_interceptor.py
# (via ck_api_rewrite.py) at intercept time, not here.
#
# Called as a library by ck_build_interceptor.py (build_lib) and
# ck_jit_build.py (quick_rebuild_lib).

import json
import os
import shlex
import shutil
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed

# ---------------------------------------------------------------------------
# Manifest helpers
# ---------------------------------------------------------------------------

def load_manifest(path):
    """
    Load manifest entries.  Supports both the NDJSON build log (path + ".ndjson")
    written by ck_build_interceptor.py and the legacy JSON-array format.
    """
    ndjson = path + ".ndjson"
    if os.path.exists(ndjson):
        entries = []
        with open(ndjson) as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        entries.append(json.loads(line))
                    except json.JSONDecodeError:
                        pass
        return entries
    with open(path) as f:
        return json.load(f)



# ---------------------------------------------------------------------------
# Compilation helpers
# ---------------------------------------------------------------------------


def link_so(hipcc, objs, out_path, arch_flags_list, rocm_lib_dir, verbose=False):
    """Link object files into a shared library."""
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    cmd = [hipcc, "-shared", "-fPIC"] + arch_flags_list + list(objs)
    if rocm_lib_dir:
        cmd += [f"-L{rocm_lib_dir}"]
    cmd += ["-lamdhip64", "-ldl", "-Wl,--allow-shlib-undefined",
            f"-Wl,-soname,{os.path.basename(out_path)}", "-o", out_path]
    print(f"[CK-POST] link: {out_path}", file=sys.stderr)
    if verbose:
        print(f"[CK-POST] link cmd: {' '.join(shlex.quote(a) for a in cmd)}", file=sys.stderr)
    r = subprocess.run(cmd, capture_output=not verbose, text=True)
    if r.returncode != 0:
        print(f"[CK-POST] ERROR linking {out_path}:\n{r.stderr}", file=sys.stderr)
    return r.returncode


# ---------------------------------------------------------------------------
# Embedded manifest header generation
# ---------------------------------------------------------------------------

def _entry_flags(entry):
    """Space-joined compile flags from the manifest entry's 'argv' field.
    argv now contains flags only (source, output, -c, and visibility flags
    were stripped at manifest-write time by ck_build_interceptor.py).
    """
    return " ".join(entry.get("argv", []))


def generate_embedded_header(entries, embedded_h, is_fwd):
    """
    Write a sorted BlobEntry header to embedded_h.
    Only blob entries for the given library direction (fwd/bwd) are included.
    Returns the number of entries written.
    """
    prefixes = ("fmha_fwd_", "fmha_batch_prefill_") if is_fwd else ("fmha_bwd_",)
    blob_entries = [
        e for e in entries
        if e.get("kind") == "blob" and
        any(os.path.basename(e.get("source", "")).startswith(p) for p in prefixes)
    ]
    blob_entries.sort(key=lambda e: os.path.basename(e["source"]))
    with open(embedded_h, "w") as f:
        f.write(
            "// Auto-generated by ck_post_build.py — do not edit\n"
            "#pragma once\n"
            "namespace ck_jit {\n"
            "struct BlobEntry { const char* name; const char* flags; };\n"
            "static const BlobEntry kEntries[] = {\n"
        )
        for e in blob_entries:
            name = os.path.basename(e['source'])
            f.write(
                f"    {{ {json.dumps(name)}, "
                f"{json.dumps(_entry_flags(e))} }},\n"
            )
        f.write(
            "};\n"
            "} // namespace ck_jit\n"
        )
    return len(blob_entries)


# ---------------------------------------------------------------------------
# Shared helpers for build_lib and quick_rebuild_lib
# ---------------------------------------------------------------------------

def _find_rocm(hipcc=""):
    """Locate hipcc and ROCm lib dir.

    If hipcc is already known, derives rocm_lib_dir from its path.
    Otherwise scans ROCM_HOME / ROCM_PATH / /opt/rocm, then PATH.
    Returns (hipcc, rocm_lib_dir).
    """
    if hipcc:
        candidate = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(hipcc))), "lib")
        return hipcc, (candidate if os.path.isdir(candidate) else "")

    rocm_lib_dir = ""
    for rocm_root in (os.environ.get("ROCM_HOME", ""),
                      os.environ.get("ROCM_PATH", ""),
                      "/opt/rocm"):
        if not rocm_root:
            continue
        if not hipcc and os.access(os.path.join(rocm_root, "bin", "hipcc"), os.X_OK):
            hipcc = os.path.join(rocm_root, "bin", "hipcc")
        if not rocm_lib_dir and os.path.isdir(os.path.join(rocm_root, "lib")):
            rocm_lib_dir = os.path.join(rocm_root, "lib")
        if hipcc and rocm_lib_dir:
            break
    if not hipcc:
        hipcc = shutil.which("hipcc") or ""
    return hipcc, rocm_lib_dir


def _derive_includes(aiter_dir, ck_include, aiter_include, rocm_include, rocm_lib_dir):
    """Fill in empty include paths from aiter_dir / rocm_lib_dir.

    Returns (ck_include, aiter_include, rocm_include, ck_fmha_include).
    """
    if aiter_dir:
        if not ck_include:
            ck_include = os.path.join(aiter_dir, "3rdparty", "composable_kernel", "include")
        if not aiter_include:
            aiter_include = os.path.join(aiter_dir, "csrc", "include")
    if not rocm_include and rocm_lib_dir:
        rocm_include = os.path.join(os.path.dirname(rocm_lib_dir), "include")
    ck_fmha_include = (
        os.path.join(os.path.dirname(ck_include), "example", "ck_tile", "01_fmha")
        if ck_include else ""
    )
    return ck_include, aiter_include, rocm_include, ck_fmha_include


def _build_runtime_cmd(hipcc, is_fwd, ck_include, ck_fmha_include,
                       aiter_include, rocm_include, build_dir, runtime_src, runtime_obj,
                       arch_flags=None):
    """Return the hipcc argv for compiling ck_jit_runtime.cpp.

    Tested against CK d5acfd8d5 and CK fdf4bb7fc.

    -DENABLE_CK=1: since CK fdf4bb7fc, aiter_hip_common.h guards real CK headers
    behind this macro (falling back to a stub shim without it).

    arch_flags must be provided when CK device headers are included (as they are
    when the dispatch functions reference ck_tile::stream_config / fmha_*_traits).
    Without --offload-arch, hipcc still triggers a device pass and CK's config.hpp
    fires a static_assert requiring exactly one arch to be defined.
    """
    cmd = [hipcc, "-std=c++20", "-fPIC", "-O2",
           f"-DCK_JIT_IS_FWD={1 if is_fwd else 0}",
           "-DENABLE_CK=1"]
    if arch_flags:
        cmd.extend(arch_flags)
    for env_var in ("CK_JIT_ROOT", "CK_JIT_NAME"):
        val = os.environ.get(env_var, "")
        if val:
            cmd.append(f'-D{env_var}="{val}"')
    if ck_include:      cmd.append(f"-I{ck_include}")
    if ck_fmha_include: cmd.append(f"-I{ck_fmha_include}")
    if aiter_include:   cmd.append(f"-I{aiter_include}")
    if rocm_include:    cmd.append(f"-isystem{rocm_include}")
    cmd += [f"-I{build_dir}", "-c", runtime_src, "-o", runtime_obj]
    return cmd


# ---------------------------------------------------------------------------
# Manifest validation: cross-check JIT hint kernel names against blob entries.
# ---------------------------------------------------------------------------

def _kernel_refs_from_source(path, root=""):
    """
    Scan a rewritten api source file for //jit_*kernel: hint comments and
    return the set of blob basenames they reference.
    For //jit_combine_kernel:, also adds the derived _lse_ variant.
    """
    if not os.path.isabs(path) and root:
        path = os.path.join(root, path)
    refs = set()
    try:
        with open(path) as f:
            for raw in f:
                s = raw.strip()
                if s.startswith("//jit_combine_kernel:"):
                    nlse = os.path.basename(s[len("//jit_combine_kernel:"):].strip())
                    refs.add(nlse)
                    lse = nlse.replace("_nlse_", "_lse_")
                    if lse != nlse:
                        refs.add(lse)
                elif s.startswith("//jit_kernel:"):
                    refs.add(os.path.basename(s[len("//jit_kernel:"):].strip()))
                elif s.startswith("//jit_dot_do_o_kernel:"):
                    refs.add(os.path.basename(s[len("//jit_dot_do_o_kernel:"):].strip()))
                elif s.startswith("//jit_convert_dq_kernel:"):
                    refs.add(os.path.basename(s[len("//jit_convert_dq_kernel:"):].strip()))
    except OSError:
        pass
    return refs


def validate_manifest(entries, root="", verbose=False):
    """
    Validate the manifest after a full build:
      - All kernel basenames referenced in //jit_*kernel: hints in api source
        files must exist as blob entries.  Missing blobs are reported as errors.
      - Blob entries not referenced by any api source are flagged as unused
        (warning only — they may be dead variants).

    Scans the rewritten _jit.cpp source files stored in api entries rather than
    relying on a kernel_names field in the manifest.

    Returns True if no errors (missing blobs), False otherwise.
    Mutates entries in-place: sets entry["unused"] = True on unused blobs.
    """
    tag = "[CK-POST]"

    blob_names = {
        os.path.basename(e["source"])
        for e in entries if e.get("kind") == "blob"
    }

    referenced = set()
    for e in entries:
        if e.get("kind") == "api":
            referenced.update(_kernel_refs_from_source(e["source"], root))

    missing = referenced - blob_names
    unused  = blob_names  - referenced

    ok = True
    for name in sorted(missing):
        print(f"{tag} ERROR: kernel '{name}' referenced by JIT hints "
              f"but not found in manifest blob entries", file=sys.stderr)
        ok = False

    for e in entries:
        bn = os.path.basename(e.get("source", ""))
        if e.get("kind") == "blob" and bn in unused:
            if verbose:
                print(f"{tag} WARNING: blob '{bn}' is in manifest but not referenced "
                      f"by any JIT hint (unused variant)", file=sys.stderr)
            e["unused"] = True

    if ok:
        print(f"{tag} Manifest validation OK: {len(referenced)} kernels referenced, "
              f"{len(unused)} unused blobs", file=sys.stderr)
    return ok


# ---------------------------------------------------------------------------
# Per-library post-build entry point (called from ck_build_interceptor at
# link-step interception time, and optionally standalone).
# ---------------------------------------------------------------------------

def build_lib(out_so, link_argv, manifest_path, jit_tmp_dir,
              runtime_src, hipcc,
              ck_include="", aiter_include="", rocm_include="",
              root="", jobs=1, verbose=False):
    """
    Produce the real out_so (libmha_fwd.so or libmha_bwd.so).

    Called once per link step from ck_build_interceptor._post_build_for_lib,
    after ninja has completed all compile steps (manifest is fully populated).

    Parameters
    ----------
    out_so        : absolute path of the .so to produce
    link_argv     : original hipcc link argv (used to extract --offload-arch
                    flags and locate real host .o files by size > 0)
    manifest_path : path to the manifest NDJSON written by the interceptor
    jit_tmp_dir   : scratch dir for rewritten sources and objects
    runtime_src   : path to ck_jit_runtime.cpp
    hipcc         : real hipcc binary
    ck_include    : CK headers root (optional; falls back to scanning api argv)
    aiter_include : aiter csrc/include (optional; same fallback)
    rocm_include  : ROCm system include dir (optional; same fallback)
    root          : AITER root dir; paths in the manifest are relative to this
    jobs          : parallel compile workers
    verbose       : print full compile commands
    """
    lib_name = os.path.basename(out_so)
    is_fwd   = "libmha_fwd" in lib_name
    tag      = "[CK-POST]"

    print(f"{tag} Building {lib_name}...", file=sys.stderr)

    # ---- Load manifest ----
    entries = load_manifest(manifest_path)
    n_blobs = sum(1 for e in entries if e.get("kind") == "blob")
    print(f"{tag} Manifest: {len(entries)} entries ({n_blobs} blobs).", file=sys.stderr)

    # ---- Arch flags: prefer link argv; fall back to first blob/api manifest entry.
    # The CXX link step (c++ -shared) does not carry --offload-arch; hipcc compile
    # steps do, so we scan manifest entries as a fallback.
    arch_fl = list(dict.fromkeys(a for a in link_argv if a.startswith("--offload-arch")))
    if not arch_fl:
        for e in entries:
            candidate = [a for a in e.get("argv", []) if a.startswith("--offload-arch")]
            if candidate:
                arch_fl = list(dict.fromkeys(candidate))
                break
    print(f"{tag} Arch flags: {arch_fl}", file=sys.stderr)

    # ---- ROCm lib dir and include paths ----
    _, rocm_lib_dir = _find_rocm(hipcc)
    ck_include, aiter_include, rocm_include, ck_fmha_include = _derive_includes(
        root, ck_include, aiter_include, rocm_include, rocm_lib_dir)

    # ---- Scratch dirs (per-lib to avoid ck_jit_runtime.o races) ----
    # Use canonical name for build_dir so ck_jit_build.py can find the state
    # file regardless of the output lib name (e.g. te_libmha_fwd.so → libmha_fwd).
    lib_name  = os.path.splitext(os.path.basename(out_so))[0]
    lib_canon = "libmha_fwd" if "libmha_fwd" in lib_name else "libmha_bwd"
    build_dir = os.path.join(jit_tmp_dir, lib_canon)
    obj_dir   = os.path.join(build_dir, "objs")
    os.makedirs(obj_dir, exist_ok=True)

    # ---- Host objects: real .o files from the ninja link command (size > 0).
    # Blob stubs are zero-byte — filtering by size excludes them.
    # Rewritten api .o files are real (non-zero) objects compiled by
    # ck_build_interceptor and will be included automatically.
    # Ninja passes object files via a response file (@path.rsp); expand lazily.
    def _iter_link_tokens(argv):
        for a in argv:
            if a.startswith("@") and os.path.exists(a[1:]):
                with open(a[1:]) as rf:
                    for tok in rf.read().split():
                        yield tok
            else:
                yield a

    host_objs = [
        a for a in _iter_link_tokens(link_argv)
        if a.endswith(".o") and os.path.exists(a) and os.path.getsize(a) > 0
    ]

    # ---- Generate embedded manifest header ----
    embedded_h = os.path.join(build_dir, "ck_jit_manifest_embedded.h")
    n_emb = generate_embedded_header(entries, embedded_h, is_fwd)
    print(f"{tag} Embedded manifest ({n_emb} entries) → {embedded_h}", file=sys.stderr)

    # ---- Validate manifest: check JIT hint kernel names against blob entries ----
    # API .o files were compiled by ck_build_interceptor (via ck_api_rewrite) at
    # intercept time and are already real non-zero-byte objects in host_objs above.
    validate_manifest(entries, root=root, verbose=verbose)

    # ---- Compile ck_jit_runtime.cpp ----
    runtime_obj = os.path.join(build_dir, "objs", "ck_jit_runtime.o")
    runtime_cmd = _build_runtime_cmd(hipcc, is_fwd, ck_include, ck_fmha_include,
                                     aiter_include, rocm_include,
                                     build_dir, runtime_src, runtime_obj,
                                     arch_flags=arch_fl)

    print(f"{tag} Compiling ck_jit_runtime.cpp...", file=sys.stderr)
    r = subprocess.run(runtime_cmd, capture_output=not verbose, text=True)
    if r.returncode != 0:
        print(f"{tag} ERROR: ck_jit_runtime.cpp:\n{r.stderr}", file=sys.stderr)
        return r.returncode

    # ---- Link ----
    # host_objs already includes the rewritten api .o files (they are non-zero-byte
    # real objects compiled by ck_build_interceptor at intercept time).
    all_objs = [o for o in host_objs + [runtime_obj]
                if os.path.exists(o)]
    rc = link_so(hipcc, all_objs, out_so, arch_fl, rocm_lib_dir, verbose)
    if rc != 0:
        return rc

    # ---- Save quick-rebuild state ----
    # Three roots for path relativisation:
    # Paths under jit_tmp_dir are stored with a {jit}/ prefix so the state file
    # is portable across moves of the tmp dir (resolved at load time via state_path location).
    state_path      = os.path.join(build_dir, "ck_jit_quick_rebuild.json")
    jit_tmp_dir_abs = os.path.abspath(os.path.dirname(build_dir))  # parent of build_dir

    def _rel(p):
        p = os.path.abspath(p)
        if jit_tmp_dir_abs and p.startswith(jit_tmp_dir_abs + os.sep):
            return "{jit}/" + os.path.relpath(p, jit_tmp_dir_abs).replace(os.sep, "/")
        return p  # absolute

    state = {
        "out_so":   _rel(out_so),
        "all_objs": [_rel(o) for o in all_objs],
        "arch_fl":  arch_fl,
    }
    with open(state_path, "w") as f:
        json.dump(state, f, indent=2)
    print(f"{tag} Quick-rebuild state → {state_path}", file=sys.stderr)

    print(f"{tag} SUCCESS: {out_so}", file=sys.stderr)
    return 0


# ---------------------------------------------------------------------------
# Quick-rebuild: recompile only ck_jit_runtime.cpp and re-link.
# ---------------------------------------------------------------------------

def quick_rebuild_lib(state_path, verbose=False, aiter_dir=""):
    """
    Recompile ck_jit_runtime.cpp and re-link the .so using the state saved by
    a previous full build_lib run.  All other object files are reused as-is.

    Parameters
    ----------
    state_path : path to ck_jit_quick_rebuild.json written by build_lib
    verbose    : print full compile/link commands
    """
    tag = "[CK-QUICK]"
    state_path = os.path.abspath(state_path)
    # build_dir  = dirname(state_path), jit_tmp_dir = dirname(build_dir)
    jit_tmp_dir = os.path.dirname(os.path.dirname(state_path))
    script_dir  = os.path.abspath(os.path.dirname(__file__))

    with open(state_path) as f:
        st = json.load(f)

    build_dir = os.path.dirname(state_path)

    aiter_dir = aiter_dir or os.environ.get("CK_JIT_AITER_DIR", "")

    def _abs(p):
        if p.startswith("{jit}/"):
            return os.path.normpath(os.path.join(jit_tmp_dir, p[6:]))
        if p.startswith("{aiter}/") and aiter_dir:
            return os.path.normpath(os.path.join(aiter_dir, p[8:]))
        if p.startswith("{script}/"):
            return os.path.normpath(os.path.join(script_dir, p[9:]))
        return p  # already absolute

    out_so   = _abs(st["out_so"])
    all_objs = [_abs(o) for o in st["all_objs"]]
    arch_fl  = st["arch_fl"]
    is_fwd   = "libmha_fwd" in os.path.basename(out_so)

    # ---- Locate hipcc, ROCm lib dir, and include paths ----
    hipcc, rocm_lib_dir = _find_rocm()
    if not hipcc:
        print(f"{tag} ERROR: hipcc not found.", file=sys.stderr)
        return 1, None

    ck_include    = os.environ.get("CK_JIT_CK_INCLUDE",    "")
    aiter_include = os.environ.get("CK_JIT_AITER_INCLUDE", "")
    rocm_include  = os.environ.get("CK_JIT_ROCM_INCLUDE",  "")
    ck_include, aiter_include, rocm_include, ck_fmha_include = _derive_includes(
        aiter_dir, ck_include, aiter_include, rocm_include, rocm_lib_dir)

    # ---- Runtime source and object paths ----
    runtime_src = os.environ.get("CK_JIT_RUNTIME_SRC",
                                 os.path.join(script_dir, "ck_jit_runtime.cpp"))
    runtime_obj = os.path.join(build_dir, "objs", "ck_jit_runtime.o")
    os.makedirs(os.path.dirname(runtime_obj), exist_ok=True)

    # ---- Regenerate generated headers from manifest ----
    embedded_h  = os.path.join(build_dir, "ck_jit_manifest_embedded.h")
    manifest_base = os.path.join(jit_tmp_dir, "manifest.json")
    if os.path.exists(manifest_base + ".ndjson"):
        entries = load_manifest(manifest_base)
        n_emb = generate_embedded_header(entries, embedded_h, is_fwd)
        print(f"{tag} Embedded manifest ({n_emb} entries) → {embedded_h}", file=sys.stderr)
    else:
        print(f"{tag} WARNING: manifest NDJSON not found; generated headers not refreshed.",
              file=sys.stderr)

    runtime_cmd = _build_runtime_cmd(hipcc, is_fwd, ck_include, ck_fmha_include,
                                     aiter_include, rocm_include,
                                     build_dir, runtime_src, runtime_obj,
                                     arch_flags=arch_fl)

    # Verify that the non-runtime objects still exist.
    missing = [o for o in all_objs if o != runtime_obj and not os.path.exists(o)]
    if missing:
        print(f"{tag} ERROR: {len(missing)} object(s) missing — run a full build first.",
              file=sys.stderr)
        for o in missing[:5]:
            print(f"  {o}", file=sys.stderr)
        return 1, None

    print(f"{tag} Recompiling {os.path.basename(runtime_src)}...", file=sys.stderr)
    if verbose:
        print(f"{tag} cmd: {' '.join(shlex.quote(a) for a in runtime_cmd)}", file=sys.stderr)
    r = subprocess.run(runtime_cmd, capture_output=not verbose, text=True)
    if r.returncode != 0:
        print(f"{tag} ERROR compiling {os.path.basename(runtime_src)}:\n{r.stderr}",
              file=sys.stderr)
        return r.returncode, None

    rc = link_so(hipcc, all_objs, out_so, arch_fl, rocm_lib_dir, verbose)
    if rc != 0:
        return rc, None
    print(f"{tag} SUCCESS: {out_so}", file=sys.stderr)
    return 0, out_so

